site_name: MobileSoftwareE21
site_url: http://localhsost:8000/
site_description: Documentation for Mobile Software
copyright: Copyright &copy; 2021

theme:
  name: material
  logo: 'https://ticketbot.xyz/static/img/logo_transparent.svg'
  palette:
    scheme: slate

  features:
    - navigation.instant
    - navigation.tabs
   # - navigation.sections
   # - navigation.expand
   # - navigation.indexes
    - search.suggest
    - search.highlight
extra:
  homepage: https://github.com/Arkobat/MobileSoftwareE21

extra_css:
  - 'stylesheets/custom.css'
  
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  
nav_disabled:
  - 'Home': './index.md'
  - 'Setup Guide': 'setup_guide.md'
  - 'Settings': 
    - 'General': 'settings/general.md'
    - 'Subjects':
      - 'Subjects': 'settings/subjects/index.md'
      - 'Ticket Template': 'settings/subjects/template.md'
    - 'Tickets': 'settings/tickets.md'
    - 'Permissions': 'settings/permissions.md'
    - 'Buttons': 'settings/buttons.md'
  - 'Commands': 'commands.md/'